import Image from 'next/image'
import Link from 'next/link'

export const metadata = { title: 'HK Advisory — Thoughtful AI. Meaningful progress.', description: 'Scientist-led AI consulting, custom Notion workspaces, and practical training with Heather Karner, PhD.' }
const services = [
  {num:'01', title:'Find your starting point.', type:'ONE-ON-ONE SESSIONS', text:'Bring the workflow that’s slowing you down. We’ll diagnose the problem, explore what AI can help with, and work toward a useful next step.', price:'$125 / hour', link:'Explore sessions'},
  {num:'02', title:'Build a system that fits.', type:'CUSTOM BUILDS & ADVISORY', text:'Connected knowledge, purposeful agents, and Notion workspaces built around your work. With documentation and guidance to make them your own.', price:'Packages from $475', link:'Explore engagements'},
  {num:'03', title:'Help your team move forward.', type:'HANDS-ON WORKSHOPS', text:'Give your lab or team a practical way into AI. Learn with real examples, ask questions, and build skills you can use in your daily work.', price:'Online or in person', link:'Explore workshops'},
]
export default function Home() { return <>
<section className="home-hero wrap">
  <div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> SCIENTIST-LED AI CONSULTING</p><h1>Thoughtful AI.<br/>Meaningful<br/><em>progress.</em></h1><p className="hero-description">Your expertise deserves tools that keep up.<br className="desktop-break"/> I help researchers, founders, and teams turn AI into practical systems for the work that matters.</p><div className="hero-actions"><Link className="editorial-button" href="/book">Let’s work together <span>↗</span></Link><Link className="text-link" href="/services">Explore services <span>→</span></Link></div><div className="hero-signature"><span className="signature-line"/><p>Heather Karner, PhD<br/><span>Scientist. Systems thinker. Your AI partner.</span></p></div></div>
  <div className="hero-visual"><div className="portrait-frame"><Image src="/images/heather-karner.jpg" alt="Heather Karner standing in a garden" fill priority sizes="(max-width: 760px) 100vw, 48vw" className="hero-portrait"/></div><div className="portrait-label"><span>SCIENCE MEETS POSSIBILITY</span><span>↗</span></div><a className="award-note" href="#orbit"><span className="award-symbol" aria-hidden="true">✳</span><div><span className="eyebrow">RECENT WIN</span><strong>Winning buildathon team</strong><span>SF Tech Week · October 2026 <b>↗</b></span></div></a></div>
</section>
<section className="credibility"><div className="wrap credibility-inner"><p>A research background.<br/><strong>A builder’s mindset.</strong></p><div><span>PhD</span><small>UC IRVINE</small></div><div><span>Research</span><small>UCSF & ARC INSTITUTE</small></div><div><span>Published</span><small>SCIENCE ADVANCES · PNAS · PATTERNS</small></div></div></section>
<section className="section-space wrap"><div className="section-intro"><p className="eyebrow">LESS FRICTION. MORE FORWARD.</p><h2>You know your work.<br/><em>Let’s make AI know it, too.</em></h2><p>Scattered information. Repetitive tasks. Tools that don’t quite connect. Together, we’ll turn the messy parts of your workflow into systems you understand and can actually use.</p></div><div className="service-grid">{services.map(s=><article className="service-panel" key={s.num}><div className="service-top"><span>{s.num}</span><span aria-hidden="true">↗</span></div><p className="eyebrow">{s.type}</p><h3>{s.title}</h3><p>{s.text}</p><div className="service-bottom"><strong>{s.price}</strong><Link href="/services">{s.link} →</Link></div></article>)}</div></section>
<section className="work-section"><div className="wrap section-space"><div className="section-heading-row"><div><p className="eyebrow">FROM IDEA TO EVERYDAY USE</p><h2>What useful AI<br/><em>looks like.</em></h2></div><p>Real projects from my consulting practice.<br/>Built for people, grounded in their work.</p></div><div className="project-grid"><article><div className="workflow-visual" aria-label="Scientific writing pipeline: refine, critique, check, review"><span>MANUSCRIPT</span><div><b>01</b> Refine the writing <i>↓</i><b>02</b> Challenge the logic <i>↓</i><b>03</b> Check citations & reproducibility <i>↓</i><b>04</b> Review statistics</div><span>HUMAN REVIEW AT EVERY STAGE</span></div><p className="eyebrow">RESEARCH & WRITING</p><h3>A second set of eyes for scientific writing.</h3><p>A multi-stage writing pipeline combining manuscript refinement, critical review, citation checks, and statistics review, with explicit guardrails against misrepresentation.</p></article><article><div className="workspace-visual"><div className="workspace-bar"><span>YOUR CONNECTED WORKSPACE</span><span>•••</span></div><div className="workspace-center"><span>Knowledge</span><span>Context</span><strong>You & your work</strong><span>Meetings</span><span>Agent skills</span></div><p>Clear context. Connected information. Practical tools.</p></div><p className="eyebrow">KNOWLEDGE & OPERATIONS</p><h3>A workspace that understands the bigger picture.</h3><p>A personalized Notion AI workspace with context pages, agent skills, meeting databases, and a knowledge base, delivered with guidance for independent daily use.</p></article></div></div></section>
<section id="orbit" className="orbit-section wrap section-space"><div className="orbit-art" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-ring ring-three"/><span className="orbit-star">✦</span><strong>ORBIT</strong><span>CONNECTIONS WITH CONTEXT</span></div><div className="orbit-copy"><p className="eyebrow">WINNING TEAM · /BUILD-WITH-AI BUILDATHON</p><h2>A good idea.<br/>90 minutes.<br/><em>A winning team.</em></h2><p>At SF Tech Week, our team built ORBIT: an AI founder networking agent that recommends connections using startup context, goals, and feedback, with persistent memory through Mem0.</p><p>I helped shape the concept, focus the demo scope, turn our brainstorming into a clear product brief, and co-present the final demo.</p><span className="orbit-caption">SF TECH WEEK / OCTOBER 2026</span></div></section>
<section className="founder-section"><div className="wrap founder-inner"><div><p className="eyebrow">MEET YOUR COLLABORATOR</p><h2>Scientific rigor.<br/><em>A human approach.</em></h2></div><div><p>I’m Heather, a PhD scientist with a background in RNA biology and cancer research. I bring the same care I put into experimental systems to AI: clear methods, thoughtful design, and tools people can use independently.</p><p>You don’t need to have it all figured out before we talk. Bring your questions, your ambition, and the workflow you wish worked better.</p><Link href="/about" className="text-link">More about Heather <span>→</span></Link></div></div></section>
<section className="section-space wrap testimonial-section"><p className="eyebrow">IN THEIR WORDS</p><blockquote>“She immediately identified where my system broke and pointed me in the right direction.”</blockquote><p className="quote-credit">Mareike S. <span> / AI workflow consulting</span></p><div className="second-quote"><blockquote>“Heather showed me how to make much better use of Notion so I could organize and integrate everything into a workflow that actually works for me.”</blockquote><p className="quote-credit">Biotech researcher & job seeker</p></div></section>
<section className="closing-section"><div className="wrap"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Make room for<br/><em>your best work.</em></h2><p>Start with one question, one workflow, or one hour.<br/>We’ll figure out the next step together.</p><Link className="editorial-button" href="/book">Let’s work together <span>↗</span></Link><small>Single sessions from $125 · No ongoing commitment required</small></div></section>
</> }
